"""add_sub_account_support

Revision ID: 515298df0811
Revises: a88da7465930
Create Date: 2026-07-07 11:27:16.640725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '515298df0811'
down_revision: Union[str, None] = 'a88da7465930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nomba_configs', sa.Column('sub_account_id', sa.String(length=255), nullable=True))
    op.add_column('wallets', sa.Column('nomba_sub_account_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'nomba_sub_account_id')
    op.drop_column('nomba_configs', 'sub_account_id')
    # ### end Alembic commands ###
