"""Add external agent transfers and one-way wallets

Revision ID: 9121542c089a
Revises: c5fd17328722
Create Date: 2026-07-05 09:15:25.635961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9121542c089a'
down_revision: Union[str, None] = 'c5fd17328722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('destination_account_number', sa.String(length=20), nullable=True))
    op.add_column('agents', sa.Column('destination_bank_code', sa.String(length=10), nullable=True))
    op.add_column('agents', sa.Column('destination_account_name', sa.String(length=255), nullable=True))
    op.add_column('wallets', sa.Column('allow_transfers_out', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'allow_transfers_out')
    op.drop_column('agents', 'destination_account_name')
    op.drop_column('agents', 'destination_bank_code')
    op.drop_column('agents', 'destination_account_number')
    # ### end Alembic commands ###
