"""remove unique constraint from nomba_account_id

Revision ID: a88da7465930
Revises: 9121542c089a
Create Date: 2026-07-06 09:55:03.265797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a88da7465930'
down_revision: Union[str, None] = '9121542c089a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('wallets_nomba_account_id_key', 'wallets', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('wallets_nomba_account_id_key', 'wallets', ['nomba_account_id'])
    # ### end Alembic commands ###
