"""initial_migration

Revision ID: c5fd17328722
Revises: 
Create Date: 2026-07-04 23:48:26.276110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5fd17328722'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_developers_email'), 'developers', ['email'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('developer_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('type', sa.Enum('live', 'test', name='api_key_type'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_developer_id'), 'api_keys', ['developer_id'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_table('nomba_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('developer_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('encrypted_client_secret', sa.Text(), nullable=False),
    sa.Column('webhook_signature_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('developer_id')
    )
    op.create_table('outbound_webhooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('developer_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('signing_secret', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('developer_id')
    )
    op.create_table('suspense_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('developer_id', sa.UUID(), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('raw_narration', sa.Text(), nullable=True),
    sa.Column('nomba_reference', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Enum('WALLET_CLOSED', 'WALLET_FROZEN', 'NO_WALLET_FOUND', 'AI_LOW_CONFIDENCE', 'AI_MISDIRECTION_SUSPECTED', 'DUPLICATE_REFERENCE', name='suspense_reason'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RESOLVED', 'FLAGGED', name='suspense_status'), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=50), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suspense_items_developer_id'), 'suspense_items', ['developer_id'], unique=False)
    op.create_index(op.f('ix_suspense_items_nomba_reference'), 'suspense_items', ['nomba_reference'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('developer_id', sa.UUID(), nullable=False),
    sa.Column('customer_reference', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('nomba_account_id', sa.String(length=255), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'FROZEN', 'CLOSED', name='wallet_status'), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nomba_account_id')
    )
    op.create_index(op.f('ix_wallets_account_number'), 'wallets', ['account_number'], unique=True)
    op.create_index('ix_wallets_developer_customer', 'wallets', ['developer_id', 'customer_reference'], unique=False)
    op.create_index(op.f('ix_wallets_developer_id'), 'wallets', ['developer_id'], unique=False)
    op.create_table('webhook_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('developer_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DELIVERED', 'FAILED', 'DEAD', name='webhook_log_status'), nullable=False),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_logs_developer_id'), 'webhook_logs', ['developer_id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_event_id'), 'webhook_logs', ['event_id'], unique=True)
    op.create_index(op.f('ix_webhook_logs_event_type'), 'webhook_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_logs_status'), 'webhook_logs', ['status'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('developer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trigger', sa.Enum('BALANCE_ABOVE', 'BALANCE_BELOW', 'ON_CREDIT', 'ON_CREDIT_AMOUNT_ABOVE', name='agent_trigger_type'), nullable=False),
    sa.Column('threshold', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.Enum('SWEEP', 'PARTIAL_SWEEP', 'WEBHOOK_NOTIFY', 'LOCK_WALLET', name='agent_action_type'), nullable=False),
    sa.Column('destination_wallet_id', sa.UUID(), nullable=True),
    sa.Column('sweep_amount', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trigger_count', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_wallet_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_developer_id'), 'agents', ['developer_id'], unique=False)
    op.create_index(op.f('ix_agents_wallet_id'), 'agents', ['wallet_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('developer_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('CREDIT', 'DEBIT', name='ledger_entry_type'), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('balance_before', sa.BigInteger(), nullable=False),
    sa.Column('balance_after', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('SETTLED', 'PENDING', 'REVERSED', name='ledger_entry_status'), nullable=False),
    sa.Column('nomba_reference', sa.String(length=255), nullable=True),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('sender_account', sa.String(length=20), nullable=True),
    sa.Column('raw_narration', sa.Text(), nullable=True),
    sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ledger_developer_created', 'ledger_entries', ['developer_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ledger_entries_developer_id'), 'ledger_entries', ['developer_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_nomba_reference'), 'ledger_entries', ['nomba_reference'], unique=True)
    op.create_index(op.f('ix_ledger_entries_wallet_id'), 'ledger_entries', ['wallet_id'], unique=False)
    op.create_index('ix_ledger_wallet_created', 'ledger_entries', ['wallet_id', 'created_at'], unique=False)
    op.create_table('agent_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('developer_id', sa.UUID(), nullable=False),
    sa.Column('trigger_event', sa.Text(), nullable=False),
    sa.Column('action_taken', sa.Text(), nullable=False),
    sa.Column('result', sa.Enum('SUCCESS', 'FAILED', name='agent_log_result'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_logs_agent_id'), 'agent_logs', ['agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_logs_agent_id'), table_name='agent_logs')
    op.drop_table('agent_logs')
    op.drop_index('ix_ledger_wallet_created', table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_wallet_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_nomba_reference'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_developer_id'), table_name='ledger_entries')
    op.drop_index('ix_ledger_developer_created', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_agents_wallet_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_developer_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_webhook_logs_status'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_event_type'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_event_id'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_developer_id'), table_name='webhook_logs')
    op.drop_table('webhook_logs')
    op.drop_index(op.f('ix_wallets_developer_id'), table_name='wallets')
    op.drop_index('ix_wallets_developer_customer', table_name='wallets')
    op.drop_index(op.f('ix_wallets_account_number'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_suspense_items_nomba_reference'), table_name='suspense_items')
    op.drop_index(op.f('ix_suspense_items_developer_id'), table_name='suspense_items')
    op.drop_table('suspense_items')
    op.drop_table('outbound_webhooks')
    op.drop_table('nomba_configs')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_developer_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_developers_email'), table_name='developers')
    op.drop_table('developers')
    # ### end Alembic commands ###
